// <auto-generated />
namespace NikhojBlog04.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Table_Added_LostPersonPosts_Comments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Table_Added_LostPersonPosts_Comments));
        
        string IMigrationMetadata.Id
        {
            get { return "201812251850524_Table_Added_LostPersonPosts_Comments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
